### ISSUE TITLE
Would not recommend blockchain.info 

### ISSUE THREAD

**Issue by omarshibli** [yellowblood/sell-bcash#1]
I would not suggest any specific wallet for the sake of neutrality and safeness.
May just refer to https://bitcoin.org/en/choose-your-wallet

**Comment by yellowblood** [comment]
As much as I want to be neutral, I also want this guide to be complete and answer the most common questions. It's a good idea to add this link but there should be detailed instructions for a specific wallet. I chose blockchain because it's very easy to import and spend the Bitcoins quickly without having to install anything.

**Comment by omarshibli** [comment]
I would suggest that the minimum level of security should be not to reveal your secret seed with any external server. this is not the case with blockchain.info .
I think this level of security shall not be compromised, It's up to you to decide.
good luck.

**Comment by yellowblood** [comment]
I agree with you. I heard such claims on blockchain in the past. In this particular case however, we're only using them to import an address and spend it quickly and easily - I'll make sure to make that clear. 

Do you have a different suggestion? I don't want to tell everyone to install a wallet.

**Comment by yellowblood** [comment]
I mean, if there's a different web-only wallet that could do the same, we can use it.

**Comment by omarshibli** [comment]
I don't know really, I use electrum and copay, both either mobile or desktop apps.

**Comment by yellowblood** [comment]
See the updated text.
