### ISSUE TITLE
Is it a good idea to sell?

### ISSUE THREAD

**Issue by 0b01** [yellowblood/sell-bcash#11]
Should I hold if everyone is selling? I don't think I'll be able to sell in time.

**Comment by earonesty** [comment]
you will, you have a lot of time, the blockchain is slow and stuttering, and there's huge peering problems, and you have to do stuff like "disablesafemode=1" in order to get it to work at all

**Comment by msmerc** [comment]
Right - there's no way to know when is the best time to sell, but the guide should point out the risks / benefits from selling now vs selling in the future.

**Comment by yellowblood** [comment]
I'm not giving trading advice. I'm explaining how to cash out the bcash for those who decided they want to.

Selling the bcash now is a bet. Holding it is also a bet. Do whatever you feel right.

**Comment by msmerc** [comment]
Right - you definitely *shouldn't* give trading advice, that would risk the ire of various financial agencies! 

However right now it appears like you're advising people to sell immediately. You should perhaps be more cautious and warn people that there is a decision to be made about when to sell for which you cannot provide advice.

**Comment by yellowblood** [comment]
@msmerc See the note I've just added, WDYT?

**Comment by msmerc** [comment]
Looks better yes. IANAL and all that but I'd probably elaborate on the risks. Something like: "Cryptocurrency trading involves substantial risk, the values can fluctuate hugely. We cannot help decide if selling BTC for BCC will be financially beneficial in the long term. All steps are taken at your own risk."

**Comment by pekatete** [comment]
No it is not a good idea, or time to sell. This whole tutorial is a scam aimed at getting people to sell their BCC on the cheap so that the authors can buy them up. Absolutely disgusting that this scam is hosted by an otherwise reputable code repository.

Best advice, BCC coins are free coins and you stand to reap even more the longer you hold. Since they are free, you stand to lose nothing.

**Comment by yellowblood** [comment]
BCC coins are indeed free coins, but if you believe the price will drop, you do have something to lose.

**Comment by pekatete** [comment]
This is a circular argument typical of scammers. This guide simply aids in flooding the market with Bitcoin Cash tokens and therefore the price will fall. Simple economics tells you that. You are creating a panic in the market and then claiming to be reacting to the panic. You created the panic so as to buy when the price is depressed due to your pre-meditated doom-mongering, fashioned to drop the price.

THIS IS A SCAM. DO NOT SELL YOUR FREE Bitcoin Cash holding.

These people simply want to create a selling frenzy so they can buy the same token on the cheap.

**Comment by yellowblood** [comment]
I give up!
THIS IS INDEED A SCAM. DO NOT SELL YOUR FREE Bitcoin Cash holdings.

...unless you want to. If you do, there's a guide for that.

😄

**Comment by pekatete** [comment]
Typical scammer making light of it all. Still, you shall be called out at every turn and the proof lies in the speed at which you closed [THIS](https://github.com/yellowblood/sell-bcash/issues/15) issue to stop any exposure.

THIS IS A SCAM.

**Comment by aaronferrucci** [comment]
My opinion: this is not a scam, it's just someone's helpful github guide. It was a good idea to state, "I am not here to give trading advice", though.

**Comment by pekatete** [comment]
@aaronferrucci - The anatomy of any good scam is typically omitting the obvious declarations that'd otherwise render the scam in-effective at the outset, but only add them after the initial wave of gullible readers have been netted or when pointed out (like you have) but the damage has already been done.

THIS IS A SCAM.

**Comment by yellowblood** [comment]
@aaronferrucci I've updated the disclaimer again, appreciate the help.

**Comment by pekatete** [comment]
The shape and form of a scam continues with no shame by having convoluted small text disclaimers appended. Do not fall for that sham.

THIS IS A SCAM.

**Comment by yellowblood** [comment]
@pekatete you're a VERY dedicated person, I'd give you that.

**Comment by aaronferrucci** [comment]
@pekatete You're only demonstrating that you believe in your opinions. You continue to state your opinions as fact, with no supporting evidence. If not for the fact that your grammar and spelling are decent, I'd have blocked you already. But your use of all caps is putting you close to the threshold.

**Comment by pekatete** [comment]
Honestly, I am not here to preach to the perpetrators, the whole idea of stopping a scam in it's tracks is to warn the prospective victims. Add to that, I have provided more than enough facts to show these coercive publications to be ill thought out scams, the onus is on the publishers to demonstrate they are not such. Whether you construe that to be just my opinion is neither here nor there, you condescending scammer. So go ahead and block me, no skin off my nose.

PLEASE BE WARNED, THIS IS A SCAM.

**Comment by pekatete** [comment]
The coercion continues.

> Although this could mean potential huge profits, this also could mean potential huge losses. Only invest money which you are willing to lose.

There is NO investment required to get Bitcoin Cash tokens for holders of bitcoin before the fork, none at all. Thus by definition there can not be any losses incurred. 

The single and only purpose of this repository is to "scare" holders into selling their free BCC tokens on the cheap by flooding the market so that the author and their contributors can then buy and hold then sell them for profit in the future.

THIS IS A SCAM.

**Comment by yellowblood** [comment]
The price drops so fast.. soon this guide will be irrelevant.

**Comment by aaronferrucci** [comment]
That reminds me - if you don't necessarily want to sell, following the first two steps of this guide is still a good idea. Some might argue that that's unnecessary - your BCC will always be on the pre-fork blockchain, right? Well, the internet abounds with stories of people who invested a few dollars in bitcoin years ago, and then lost track of their private keys. I could easily see myself transferring my BTC from wallet to wallet, and eventually losing the key for that all-important last wallet before the fork.

What do you think of a brief note at the end of step 2, "stop here if you just wanted to secure your BCC in a separate wallet"? If you don't veto the concept, I'll put together a pull request.

**Comment by yellowblood** [comment]
@aaronferrucci I've added a line in the disclaimer - `However, it still advised to follow steps 1 and 2 to move your BCash to a new address.`

**Comment by yellowblood** [comment]
If you feel it's not enough or have other suggestions - let's work it out on a Pull Request.
