### ISSUE TITLE
use a trustworthy bcash wallet

### ISSUE THREAD

**Issue by aaronferrucci** [yellowblood/sell-bcash#8]
There may be no better bcash wallet than Electron right now - but when I see statements like, 

> ... we cannot trust this app fully - it may steal your Bitcoins...

it makes me a bit nervous! When a trustworthy wallet exists, the guide should switch to it.

Also, the Electron wallet folks warn:

> Be especially carefully running both Electron Cash and Electrum at the same time.

This hints that there may be unintended interactions between Electrum and Electron... might be worth an extra note in the guide.

**Comment by yellowblood** [comment]
I should rephrase. There are no evidences of Electron Cash stealing as far as I know, it's just not around enough to be trustworthy. Thanks a lot for the feedback.

Feel free to create a PR if you want to rephrase anything yourself.

**Comment by Mirobit** [comment]
Electron is partly developed by Neil Booth (@kyuupichan). He has been involved in the Electrum development for a while and I think that he is trustworthy. So it is highly unlikely that Electron is or will be a wallet stealer.
The issue is that Electron is a new software with very little peer review and testing. The warning should reflect that there might be bugs that led to the loss of coins. The "stealing part" should be removed. I will try to rephrase this later.

**Comment by yellowblood** [comment]
@Mirobit - very good points, thank you. Will update the guide with better phrasing.

**Comment by earonesty** [comment]
i added instructions for doing it from source code.   much safer, and not that hard.
